### ISSUE TITLE
Faker not found after exposing factories

### ISSUE THREAD

**Issue by mkasztelnik** [dice-cyfronet/atmosphere#104]
It seems like #97 introduces small bug (Faker dependency missing).

We can add faker into dependencies list, but it is used only in `test` environment. @Nuanda any proposition how we can add it only to this environment?

```
λ leeloo atmosphere → λ git master → bundle exec rake db:drop db:create db:migrate db:seed
rake aborted!
NameError: uninitialized constant Faker
/home/marek/git/atmosphere/spec/factories/http_mappings.rb:3:in `block (2 levels) in <top (required)>'
/home/marek/git/atmosphere/spec/factories/http_mappings.rb:2:in `block in <top (required)>'
/home/marek/git/atmosphere/spec/factories/http_mappings.rb:1:in `<top (required)>'
/home/marek/git/atmosphere/spec/dummy/config/environment.rb:5:in `<top (required)>'
Tasks: TOP => db:migrate => app:db:migrate => app:environment
(See full trace by running task with --trace)
```

**Comment by Nuanda** [comment]
What's the severity of this? Does it stop you from running specs in Atmo?

**Comment by mkasztelnik** [comment]
It is quite high. E.g. I'm not able to recreate development database for `spec/dummy` project.

**Comment by Nuanda** [comment]
Can you tell me how to recreate this? In spec/dummy I get 'development' database is not configured - I only use it for tests.

**Comment by mkasztelnik** [comment]
you should have something like:

```
development:
  <<: *default
  database: atmosphere_development
```

in `spec/dummy/config/database.yml` and next invoke following command:

```
bundle exec rake db:drop db:create db:migrate db:seed
```

**Comment by Nuanda** [comment]
Yes, figured that out. Still it does not work due to some migration problem, but I'm able to recreate the problem.
