### ISSUE TITLE
Invalid exception Air::UnsuportedException in raised when operation is not supported on a given compute site

### ISSUE THREAD

**Issue by tbartynski** [dice-cyfronet/atmosphere#110]
I guess we no longer have Air::UnsuportedException. It should be refactored into Atmosphere::UnsupportedException.

**Comment by mkasztelnik** [comment]
If you have time than sure

**Comment by tbartynski** [comment]
Implemented. See https://github.com/dice-cyfronet/atmosphere/pull/111
