### ISSUE TITLE
Inspect why redoing migrations lost hourly cost data

### ISSUE THREAD

**Issue by tbartynski** [dice-cyfronet/atmosphere#124]
We needed to redo migration on dev and we've redone:
20150218172346_move_prepaid_until_to_deployments.atmosphere.rb
20150218172347_add_osfamilies.atmosphere.rb
20150225145727_add_osfamily_to_dev_mode_property_sets.atmosphere.rb

Data about houlry cost was lost by this operation and Atmosphere failed to even show a list of appliance type. This has been fixed by setting hourly cost to the amount of RAM of the associated flavor. This may require setting real costs.

**Comment by tbartynski** [comment]
Related issue:
https://github.com/dice-cyfronet/atmosphere/issues/125

**Comment by mkasztelnik** [comment]
@tbartynski I believe this issue is already fixed by refreshing `ApplianceType` mapping into DB in the migration. Am I right?

**Comment by mkasztelnik** [comment]
@tbartynski, @nowakowski your assistance is needed here.

**Comment by tbartynski** [comment]
Already fixed.
