### ISSUE TITLE
Server error when deleting appliance set with 1 appliance via Atmo gui

### ISSUE THREAD

**Issue by tbartynski** [dice-cyfronet/atmosphere#126]
It seemed like after AS was destroyed I was redirected to view it.

**Comment by mkasztelnik** [comment]
Can you extract error message from production logs?

**Comment by tbartynski** [comment]
I, [2015-03-18T13:33:36.507573 #3269]  INFO -- : Started DELETE "/admin/appliance_sets/990" for 127.0.0.1 at 2015-03-18 13:33:36 +0100
I, [2015-03-18T13:33:36.509945 #3269]  INFO -- : Processing by Atmosphere::Admin::ApplianceSetsController#destroy as HTML
I, [2015-03-18T13:33:36.510010 #3269]  INFO -- :   Parameters: {"authenticity_token"=>"vXLuZnGT6/tKf9N4q9W1yF6D1hAatSsij5IXKsC+QkE=", "id"=>"990"}
I, [2015-03-18T13:33:36.528347 #3269]  INFO -- : Completed 404 Not Found in 18ms
I, [2015-03-18T13:33:36.529440 #3269]  INFO -- : ** [Raven] User excluded error: #<ActiveRecord::RecordNotFound: Couldn't find Atmosphere::ApplianceSet with 'id'=990>
F, [2015-03-18T13:33:36.533753 #3269] FATAL -- :
ActiveRecord::RecordNotFound (Couldn't find Atmosphere::ApplianceSet with 'id'=990):

I have the rest of the log but it's meaningless.

**Comment by mkasztelnik** [comment]
@tbartynski I'm trying to recreate this issue. Unfortunately without success. In the appliance sets controller I see that after removing AS it redirects into appliance sets view, no to selected appliance set.

Can you try to recreate this issue and post steps which I need to perform to recreate it?

**Comment by mkasztelnik** [comment]
@tbartynski your assistance is needed here

**Comment by tbartynski** [comment]
Unfortunately I cannot give any extra information besides that in admin gui I viewed appliance sets. Then I deleted one appliance set and my browser was redirected to view the set I just deleted. The appliance set was created by the nagios probe but that should not change anything.

If you cannot reproduce the error reject this issue. If it happens again I'll try to collect more data about it.

**Comment by mkasztelnik** [comment]
Ok, please if it repeats please write down steps required to recreate it :smile:
