### ISSUE TITLE
Billing flags moved from Appliance to Deployment PR upgrade is not automatic

### ISSUE THREAD

**Issue by mkasztelnik** [dice-cyfronet/atmosphere#142]
When atmosphere upgrade includes #68 than DB state is in invalid state. Following exception is thrown to the user while trying to get optimal flavor:

```
F, [2015-04-10T13:26:39.813702 #29264] FATAL -- : 
NoMethodError (undefined method `>' for nil:NilClass):
  vendor/bundle/ruby/2.1.0/bundler/gems/atmosphere-84b8e392d767/lib/atmosphere/utils.rb:7:in `block in min_elements_by'
  vendor/bundle/ruby/2.1.0/bundler/gems/atmosphere-84b8e392d767/lib/atmosphere/utils.rb:5:in `each'
  vendor/bundle/ruby/2.1.0/bundler/gems/atmosphere-84b8e392d767/lib/atmosphere/utils.rb:5:in `min_elements_by'
  vendor/bundle/ruby/2.1.0/bundler/gems/atmosphere-84b8e392d767/app/providers/atmosphere/optimization_strategy/default.rb:76:in `block in select'
```

It is connected with `FlavorOsFamily.hourly_cost` equals to `nil`. First of all this value should not be allowed to be `nil`, secondly `AddOsfamilies` migration should update this value on new created object.

@nowakowski - please, please, please take into account that we are losing a lot of time thanks to this kind of surprises (up to now twice multiplied by 1 to 2 hours lost by me and @tbartynski). Possible solutions as as follow:

  * ugly one:

```ruby
Atmosphere::FlavorOSFamily.all.each { |f| f.hourly_cost = f.virtual_machine_flavor.memory }
```

  * better one: in `up` method after `FlavorOSFamily` is created assign `hourly_cost` from `VirtualMachineFlavor.hourly_cost`. In `down` firstly add `VirtualMachineFlavor.hourly_cost` check max value from `FlavorOSFamily.hourly_cost` and at the end remove `FlavorOSFamily`. 

/cc @dice-cyfronet/atmo-dev-team - if any of you is doing upgrade which includes #68 please read it

**Comment by mkasztelnik** [comment]
Title and PR number corrected

**Comment by nowakowski** [comment]
@mkasztelnik The problem was caused by a naming clash between `VirtualMachineFlavor.hourly_cost` (an AR method) and `atmosphere_virtual_machine_flavors.hourly_cost` (a model attribute). The migration relied on accessing the old (obsolete) attribute via model class invocation but the method defined in `virtual_machine_flavor.rb` was invoked instead, returning *nil* instead of the (expected) attribute value. The reason I missed this issue is because the extra method was added *after* the migration, and rspec does not test migrations. Fixing.

**Comment by mkasztelnik** [comment]
Great, thx for the explanation :smile: 

BTW take a loot at https://github.com/dice-cyfronet/atmosphere/pull/151. I'm just testing it - it should solve a lot of problems with copying migrations from atmosphere into project which uses atmosphere.
