### ISSUE TITLE
Atmosphere factories requires ffaker

### ISSUE THREAD

**Issue by mkasztelnik** [dice-cyfronet/atmosphere#153]
As @Nuanda correctly noted in https://github.com/dice-cyfronet/atmosphere/pull/141#issuecomment-93528661 Atmosphere factories [exposed to other RoR apps in test env](https://github.com/dice-cyfronet/atmosphere/pull/97) requires ffaker (after #141 will be merged ffaker 2.0.0). 

I'm not sure how such dependency can be defined in gemfile. We cannot add it as runtime dependency, because it is required only in test env. On the other hand defined it as development dependency will not solve the issue, since it is not propagated. 

The only solution I see right now is to add note that ffaker is required, if you want to use factories exposed by Atmoshere, into README. 

@dice-cyfronet/atmo-dev-team do you have any other proposition how to solve this issue?

**Comment by Nuanda** [comment]
And we may force 2.0.0+ ffaker version in all atmo-dependent project Gemfiles we know.

**Comment by mkasztelnik** [comment]
Done for vph in https://github.com/VPH-Share/atmosphere-vph/commit/a3c5056e07ba75018441b93022443df86c3c0ef9

**Comment by mkasztelnik** [comment]
Done for imsop in https://github.com/ismop/exp/commit/b253e2f6e5a00f93160d61a8f11f2d397b77195a

**Comment by mkasztelnik** [comment]
Done for plgrid in [77028809a018e60ad93fe3449d1055b48818cc6f](https://gitlab.dev.cyfronet.pl/atmosphere/plgrid/commit/77028809a018e60ad93fe3449d1055b48818cc6f)
