### ISSUE TITLE
Enable redirecting http traffic to secured upstream servers

### ISSUE THREAD

**Issue by dharezlak** [dice-cyfronet/atmosphere#154]
Currently only http upstream servers can be used. This will require to also change the external interface configuration form in MI's cloud views and atmosphere's REST API to convey the additional attribute saying if the upstream server is secured with https.

**Comment by mkasztelnik** [comment]
With @dharezlak we performed test where `https->proxy->https->vm` communication was established.

Redirus is ready for such change. Options capability can be used to distinguish if `http` or `https` should be used in `proxy_pass` directive. The only thing needed here is to change templates.

Atmosphere on the other hand need to be changed to support this feature. Boolean value should be added into `Port Mapping Template` (e.g. `upstream_https`) and this value should be converted into option while sending request into Redirus.

**Comment by mkasztelnik** [comment]
@nowakowski, @tbartynski this task priority should be increased. In plgrid we have a situation where https->https communication should be established. 

Another solution of the problem would be to:
  - remove `https`/`https` `PortMappingTemplate` type, only `http` **OR** `https`
  - redirus will establish `http`->`http` or `https`->`https` communication.

What is your opinion?

**Comment by nowakowski** [comment]
Can we establish `https`->`https` without triggering a MIM-type situation?

**Comment by mkasztelnik** [comment]
Yeap, I was able to establish such connection before creating this issue. To be 100% sure we can recreate such situation on Monday :smile:

**Comment by nowakowski** [comment]
That's good news. I like the idea of removing `HTTP and HTTPS`; IMHO this option never made much sense. :)

**Comment by mkasztelnik** [comment]
I have mixed filings about it. On one hand you are right, for user it is quite strange that https->http connections are created. On the other hand https->http is much faster than https->https and we can treat inter tenant communication as "safe".

**Comment by nowakowski** [comment]
@mkasztelnik I fully agree; what I was trying to say is that it's weird to have **both** an HTTP and an HTTPS redirection to an application service (you'll typically want one or the other); hence this menu option is confusing and could be removed.
