### ISSUE TITLE
New user key form rendered with error after an attemp to add DSA key

### ISSUE THREAD

**Issue by tbartynski** [dice-cyfronet/atmosphere#164]
DSA keys are not supported. If one tries to add a DSA key an appropriate error message is displayed and form for adding a new key is shown with all fields filled with content. User selector widget is broken a bit however. It displays DB ids of users instead of their logins. It displays login fine for the first time.

**Comment by mkasztelnik** [comment]
Can you describe how I can recreate this issue?

**Comment by tbartynski** [comment]
Try adding a new user key in the UI. Generate a DSA type public key instead of a RSA (which is the default).
