### ISSUE TITLE
Figure out a way to recreate .ssh/authorized_keys when storing VMs so that developer keys are not preserved in new ATs. 

### ISSUE THREAD

**Issue by nowakowski** [dice-cyfronet/atmosphere#200]

**Comment by mkasztelnik** [comment]
@nowakowski can you elaborate more about this issue? Please describe the problem and possible solutions.

**Comment by nowakowski** [comment]
The issue is that any leftover keys added by service developers to `.ssh/authorized_keys` are serialized along with the VM's filesystem so the developers obtain an illicit backdoor to any future instances launched in the cloud. I don't really see a way to automate this task with existing tools - cloud-init doesn't handle it properly - so perhaps we can warn developers to scrub the key file prior to saving a new template?

**Comment by mkasztelnik** [comment]
The problem with authorized key is not specific to atmospehre itself but to used cloud providers. E.g. on google cloud user key can be injected into VM after VM is started. Of course this is specific mechanism started on VM, thus VM author can disable it. 

I propose to close this issue.

**Comment by nowakowski** [comment]
Yeah, I realize it can be done in special cases, but special cases suck. Agreed. Closing.
