### ISSUE TITLE
Add unique identifier to error log AND alert popup. 

### ISSUE THREAD

**Issue by bwilk** [dice-cyfronet/atmosphere#208]
It may be usefull to add unique identifier to error log AND alert popup to allow developers to correlate error effect with the cause. In this way the user reports the error ID and all we have to do in order to find the error cause, is to search through logs for that ID. 
It would be a neat enhancement.

**Comment by mkasztelnik** [comment]
Good point, I can deal with it

**Comment by mkasztelnik** [comment]
Request id is already added into every response as `X-Request-Id`. Every application which uses atmosphere can configure log formatter to add this id into every log entry. To do so following modification is needed: in `config/environments/production.rb` add following line:

```ruby
config.log_tags = [:uuid]
```

The only remaining thing to do here is to show request id to the user. @dharezlak promise to deal with it.
