### ISSUE TITLE
Unable to add property to port mapping template created in dev mode

### ISSUE THREAD

**Issue by mkasztelnik** [dice-cyfronet/atmosphere#219]
When appliance is started in development mode user is able to add port mapping template. Unfortunately  it is not possible to add port mapping property (ability does not implement such case, see https://github.com/dice-cyfronet/atmosphere/blob/master/app/abilities/atmosphere/port_mapping_property_ability_builder.rb#L15). 

This issue was discovered by @donpiekarz during security audit - thx :smile: 

@tbartynski can you take care of this issue next week?

**Comment by tbartynski** [comment]
Will do that.

**Comment by tbartynski** [comment]
Will
