### ISSUE TITLE
While creating an appliance it should be checked if chosen opt strategy supports dev mode

### ISSUE THREAD

**Issue by tbartynski** [dice-cyfronet/atmosphere#245]
For instance manual strategy can not be used in dev mode. While instantiating an appliance object it should check whether chosen policy support dev mode.

**Comment by tbartynski** [comment]
Create a class method in Default policy:
supports_dev_mode? that returns true.
Other implementations of optimization policies should extend Default policy and override if necessary that method.
Manual.supports_dev_mode? should return false.
While creating appliance it should be validated:
if appl.development && !appl.opt_policy.supports_dev_mode
  raise error
end

**Comment by mkasztelnik** [comment]
I propose to generalize this method like this:

```
def support?(as)
  as.production?
end
```

**Comment by tbartynski** [comment]
Ok. Any suggestions what error should be raised? Atmosphere::UnsupportedException?

**Comment by mkasztelnik** [comment]
It was agreed that this check will be done as model validation

**Comment by tbartynski** [comment]
Pull request ready for review.
