### ISSUE TITLE
"Show this Virtual Template" does not work

### ISSUE THREAD

**Issue by patrykl** [dice-cyfronet/atmosphere#263]
On the "Templates" tab, clicking "Show this Virtual Template" gives an error.
In the logs:

[2015-09-15T11:32:01.740591 #13741]  INFO -- : Started GET "/admin/virtual_machine_templates/3" for 127.0.0.1 at 2015-09-15 11:32:01 +0200
I, [2015-09-15T11:32:01.742913 #13741]  INFO -- : Processing by Atmosphere::Admin::VirtualMachineTemplatesController#show as HTML
I, [2015-09-15T11:32:01.743012 #13741]  INFO -- :   Parameters: {"id"=>"3"}
I, [2015-09-15T11:32:01.760255 #13741]  INFO -- :   Rendered vendor/bundle/ruby/2.2.0/bundler/gems/atmosphere-f133a0e26122/app/views/atmosphere/admin/virtual_machine_templates/show.html.haml within layouts/atmosphere/application (2.8ms)
I, [2015-09-15T11:32:01.760581 #13741]  INFO -- : Completed 500 Internal Server Error in 17ms (ActiveRecord: 1.1ms)
F, [2015-09-15T11:32:01.793002 #13741] FATAL -- : 
ActionView::Template::Error (undefined method `tenant' for #<Atmosphere::VirtualMachineTemplate:0x007fa846603498>):
    2:   %table.show-table
    3:     %tr
    4:       %td= t('virtual_machine_templates.tenant')
    5:       %td= @virtual_machine_template.tenant
    6:     %tr
    7:       %td= t('uuid')
    8:       %td.monospace= @virtual_machine_template.id_at_site

**Comment by mkasztelnik** [comment]
This is already fixed https://github.com/dice-cyfronet/atmosphere/blob/master/app/views/atmosphere/admin/virtual_machine_templates/show.html.haml#L5 here: https://github.com/dice-cyfronet/atmosphere/commit/a6affc90f43dd45d7a35bc8455d6e67cb235215c
