### ISSUE TITLE
Verify issues fixed after security audit

### ISSUE THREAD

**Issue by mkasztelnik** [dice-cyfronet/atmosphere#265]
* [x] @nowakowski  1
  * [x] @nowakowski  2
  * [x] @mkasztelnik  3
  * [x] @nowakowski 4
  * [x] @mkasztelnik 5
  * [x] @mkasztelnik 6
  * [x] @tbartynski 7
  * [x] @nowakowski 8
  * [x] @tbartynski 9
  * [x] @nowakowski 10
  * [x] @mkasztelnik 11
  * [x] @nowakowski 12
  * [x] @mkasztelnik 13
  * [x] @mkasztelnik 14
  * [x] @mkasztelnik 15
  * [x] @nowakowski 16
  * [x] @mkasztelnik 17
  * [x]  @nowakowski 18

**Comment by nowakowski** [comment]
@mkasztelnik Do these ticks indicate that the given vulnerability has been confirmed as fixed?

**Comment by mkasztelnik** [comment]
Yeap

**Comment by nowakowski** [comment]
roger

**Comment by mkasztelnik** [comment]
@nowakowski, @tbartynski  ping!!!

**Comment by nowakowski** [comment]
Well, I've done a few - perhaps @tbartynski can pitch in? If not, I'll work on the remaining ones later today.

**Comment by nowakowski** [comment]
Done retesting my assigned vulnerabilities.

**Comment by tbartynski** [comment]
Wow! We are grate! Someone has ticked the 3rd vulnerability before I implemented a fix for it!!

**Comment by nowakowski** [comment]
@tbartynski Oops, that was me - I was re-ticking my vulnerabilities which someone had so kindly unticked for me. ;)
