### ISSUE TITLE
Cannot upate external interface in clew

### ISSUE THREAD

**Issue by tbartynski** [dice-cyfronet/atmosphere#272]
I've added an external interface. Then I clicked Edit external interface for the added interface and changed proxy send  and read timeouts and clicked update. Result:
Unexpected error occurred
Object is invalid
Request ID: 475be631-6f43-43cc-b94b-504b87c9ef06
When reporting this issue use the provided request ID
Details
key:has already been taken

**Comment by mkasztelnik** [comment]
@tbartynski can you explain what is wrong here?

**Comment by tbartynski** [comment]
I was able to reproduce this error on exp.moc.ismop.edu.pl. I created an external interface for a running VM. Then I cannot update it's properties. It seems like CLEW tries to create new external interface instead of updating existing one hence the "key:has already been taken" error.

**Comment by mkasztelnik** [comment]
@dharezlak can you take a look?

**Comment by dharezlak** [comment]
Testing (help needed):

1. `GET /port_mapping_properties?port_mapping_template_id=242` => {"port_mapping_properties": []}
2. `POST /port_mapping_properties {"port_mapping_property":{"port_mapping_template_id":"242", "key":"proxy_send_timeout", "value":"600"}}` => `{... {"key": ["has already been taken"]} ...}`

So, if I understand this correctly, the POST in step 2 should succeed as there are no previous properties present, right?

**Comment by mkasztelnik** [comment]
I will take a look at this issue

**Comment by mkasztelnik** [comment]
Exp was using quite old atmosphere version. After upgrading into latest atmosphere I cannot reproduce this issue.
