### ISSUE TITLE
Additional VirtualMachineFlavor parameters

### ISSUE THREAD

**Issue by nowakowski** [dice-cyfronet/atmosphere#28]
The `Atmosphere::VirtualMachineFlavor` model should be extended with additional parameters to permit more robust deployment of services on Amazon. I propose adding the following:
* an enum field called `os_type` to `Atmosphere::ApplianceType` and a foreign key in `Atmosphere::VirtualMachineFlavor` linking to a new dictionary table 'Atmosphere::OSTypes`. Additionally, the `hourly_cost` field would be moved from `Atmosphere::VirtualMachineFlavors` to the newly created table. This would enable us to support different flavor prices for different operating systems.
* An enum field called `optimization_policy` to `Atmosphere::ApplianceType` which would enable the Optimizer to make a more informed selection of the applicable EC2 flavors (note that Amazon flavors can be storage-optimized, memory-optimized, network-optimized etc.)

Comments?

**Comment by mkasztelnik** [comment]
@nowakowski I believe this is already fixed in #119 - can we close it?

**Comment by nowakowski** [comment]
@mkasztelnik Indeed - closing.
