### ISSUE TITLE
Info about possibility to input numbers in a form

### ISSUE THREAD

**Issue by patrykl** [dice-cyfronet/atmosphere#288]
Users don't know they are able to input numbers not only to choose from a drop-down.
Would be nice to change i.e. "Number of cores (optional)" to "Choose or enter number of cores (optional)"

**Comment by dharezlak** [comment]
Reassigning to @bwilk to build an rpm package with this change.

**Comment by dharezlak** [comment]
When #290 is built this fix will be also included in the package.
