### ISSUE TITLE
Create a VM using API

### ISSUE THREAD

**Issue by groundnuty** [dice-cyfronet/atmosphere#303]
After studding the [API](https://github.com/dice-cyfronet/atmosphere/blob/master/doc/api/virtual_machines.md) I cannot find the way to create VMs?
When creating/destroying a number of VMs regularly using a web interface is quite a burden. 
Have I missed something or this feature is not yet implemented?

**Comment by mkasztelnik** [comment]
You should create appliance. After it is created optimizer is started and optimizer decides which VM(s) should be started.
