### ISSUE TITLE
Asynchronous VM creation as a result of optimize action

### ISSUE THREAD

**Issue by mkasztelnik** [dice-cyfronet/atmosphere#54]
Currently the process of appliance optimization is a synchronous process. It heavily dependent on the compute site response time - this is bad, because user request can take a long time blocking other requests (this situation was discovered by @dharezlak during Atmosphere performance tests). 

My proposition it to move all cloud actions into delay job. As a conclusion the result of the optimization process will be a set of delay jobs which should be executed in asynchronous way. This approach have additional challenges to solve:
  - race conditions between 2 optimizer run
  - when to bill appliance? After every VM spawned for appliance, in defined period of time?
  - what kind of `state` and `state_explanation` should be set in `appliance` when optimizer finished but actions are not executed yet?

@tbartynski, @bwilk, @nowakowski, @Nuanda please take a look at [`ApplianceVmsManager`](https://github.com/dice-cyfronet/atmosphere/blob/master/app/services/atmosphere/appliance_vms_manager.rb) and report back with your remarks, propossitions.

**Comment by mkasztelnik** [comment]
Take a look at #63 which is connected with this issue.

**Comment by tbartynski** [comment]
Resolved while implementing enhancements in Atmosphere.

**Comment by mkasztelnik** [comment]
It is done in #218
