### ISSUE TITLE
Atmosphere integration with other components documentation

### ISSUE THREAD

**Issue by mkasztelnik** [dice-cyfronet/atmosphere#67]
Right now we have nice generic documentation for Atmosphere created in the scope of #64. We also need to create more detailed description how Atmosphere is integrated with external elements:
- [x] [Atmosphere user interface](https://github.com/dice-cyfronet/clew) - here we should describe how to embed `clew`
- [ ] integration with [Redirus](https://github.com/dice-cyfronet/redirus)
- [ ] integration with [IPWrangler](https://github.com/dice-cyfronet/ipt-wrangler)
- [ ] User interface documentation for Atmosphere internal views
- [ ] [Migratio](https://github.com/dice-cyfronet/migratio) - describe how to migrate VMT from one compute site to another.

We should also consider moving `clew` and `IPWrangler` into github to simplify link creation between projects.

/cc @dharezlak, @paoolo, @nowakowski

**Comment by paoolo** [comment]
``IPWrangler`` is moved to GitHub on https://github.com/dice-cyfronet/ipt-wrangler

I guees that we need to unify naming of projects.

**Comment by mkasztelnik** [comment]
@dice-cyfronet/atmo-dev-team any volunteer for this task?

**Comment by Nuanda** [comment]
Regarding bullet number 4 - documentation for admin views. I am against external doc in the form of a manual. Having more contextual help and some documentation _embedded_ in the views themselves would, in my opinion, serve the users better.

**Comment by mkasztelnik** [comment]
@Nuanda I agree. Can you create separate issue connected with your proposition and link it with this issue?

**Comment by Nuanda** [comment]
@nowakowski i think you were preparing some admin docs for future PLGrid Atmo administrators - can you point me to that document?

**Comment by mkasztelnik** [comment]
Marking first bullet as completed, since clew is embedded into atmosphere already.

**Comment by pasuder** [comment]
I guess that could be closed after so long inactivity.
