### ISSUE TITLE
SIGTERM in development enviroment

### ISSUE THREAD

**Issue by paoolo** [dice-cyfronet/atmosphere#79]
Logs available at https://gist.github.com/paoolo/057dcf853db09ebcfe32

**Comment by paoolo** [comment]
@dice-cyfronet/atmo-dev-team please take a look

**Comment by mkasztelnik** [comment]
Can you describe steps which will allow me to recreate this problem?

**Comment by paoolo** [comment]
Start and wait if this problem occurs. No redis server was running 
during this scenario.

**Comment by paoolo** [comment]
To start use scripts `spec/dummy/bin/run-environment`.

**Comment by mkasztelnik** [comment]
or simple `cd spec/dummy; foreman start` :smiling_imp:

**Comment by paoolo** [comment]
Buah buah :D

**Comment by paoolo** [comment]
Update. See: https://gist.github.com/paoolo/057dcf853db09ebcfe32#file-atmosphere-development-2015-01-15_09-58-log

**Comment by mkasztelnik** [comment]
I believe that we can close it since it describe situation when precondition requirements are not met for atmosphere.
