### ISSUE TITLE
Disable Hound CI checking changes in `schema.rb`

### ISSUE THREAD

**Issue by paoolo** [dice-cyfronet/atmosphere#86]
For files:

* `db/schema.rb`
* `spec/dummy/db/schema.r`

See: https://github.com/thoughtbot/hound/issues/480

@Nuanda, @mkasztelnik  What are you thinking about this?

**Comment by mkasztelnik** [comment]
I think that exclude for `schema.rb` is a good solution - go for it :sunglasses:. Also configuration of `hound-tools` looks nice - can you try to configure atmosphere to use it?

**Comment by paoolo** [comment]
I will try it.

**Comment by paoolo** [comment]
PR #94 created. How to check this how it works if Hound verify only committed changes, not whole project?

**Comment by paoolo** [comment]
Closed via #94
