### ISSUE TITLE
Inform user about destructive operation side-effects

### ISSUE THREAD

**Issue by paoolo** [dice-cyfronet/atmosphere#90]
After removing Compute Site from Atmosphere, VMTs located on that Compute Site are removed. I guess that flag `managed_by_atmosphere` decided if the VMT will be removed or not. But there is no information displayed for admin about side-effects of removing Compute Site.

/cc @nowakowski @mkasztelnik @Nuanda what are you thinking about informing admin about side-effects of some operation performed via Atmosphere?

**Comment by mkasztelnik** [comment]
Agree - it can be added into confirmation popup

**Comment by nowakowski** [comment]
Indeed, a "molly guard" would be useful in this context.

**Comment by mkasztelnik** [comment]
Any volunteer to implement it?

**Comment by nowakowski** [comment]
I surrender and volunteer for treason!

**Comment by paoolo** [comment]
I guess that the same information should be displayed when user want to delete Appliance Type. What if Appliance Type handled important Virtual Machine Template? More: what if admin want to remove Virtual Machine Template from Appliance Type without removing it from Compute Site? See #91.
