### ISSUE TITLE
Cannot remove VMT from Appliance Type

### ISSUE THREAD

**Issue by paoolo** [dice-cyfronet/atmosphere#91]
```
ActionController::RoutingError (No route matches "https://vph-dev.cyfronet.pl/admin/appliance_types/118"):
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/routing/route_set.rb:718:in `recognize_path'
  vendor/bundle/ruby/2.1.0/bundler/gems/atmosphere-98e0c2fb030a/app/controllers/atmosphere/admin/virtual_machine_templates_controller.rb:39:in `update'
[...]
```

How this operation works? Does it remove VMT from AT and remove VMT from CS? See #90

**Comment by mkasztelnik** [comment]
After `ApplianceType` is deleted all `VirtualMachineTemplates` with `managed_by_atmosphere` flag set to `true` are removed from compute site. Take a look at [`delete_vmts`](https://github.com/dice-cyfronet/atmosphere/blob/master/app/models/atmosphere/appliance_type.rb#L192-L196) method invoked by `around_destroy :delete_vmts` callback.

Does it answer your question?

**Comment by mkasztelnik** [comment]
Can you explain in more details nature of reported bug? How I can recreate it?

**Comment by paoolo** [comment]
Try to remove VMT from Templates on Appliance Type. Tested VMT has flag `managed_by_atmosphere` set to `True`.

**Comment by nowakowski** [comment]
This should cause the VMT manager worker to delete the template from the cloud site.

**Comment by mkasztelnik** [comment]
Ok so correct scenario how to recreate it is as follow:

1. create appliance type
2. assign VMT to appliance type
3. try to remove relation between VMT and appliance type

@Nuanda can you take a look at this issue?

**Comment by paoolo** [comment]
@mkasztelnik said that in this case should be remove the relation between VMT and AT. I proposed  change the name of this operation from "Remove...assignment" to "Deregister this VMT from this AT".

**Comment by Nuanda** [comment]
Well, you can assign it to me if you think I should try to recreate the problem and diagnose the cause. However, I never did anything related to cloud-management workers in Atmo so I doubt I'll be able to help with mitigating the issue.

**Comment by mkasztelnik** [comment]
@Nuanda the problem is connected with this code:

```ruby
if Rails.application.routes.recognize_path(request.referrer)[:controller] == 'admin/appliance_types'
        redirect_to request.referer
```

in [`VirtualMachineTemplatesController`](https://github.com/dice-cyfronet/atmosphere/blob/master/app/controllers/atmosphere/admin/virtual_machine_templates_controller.rb#L39-L40), that is why I was asking you to take a look at it.

**Comment by Nuanda** [comment]
@mkasztelnik Thanks for fixing this. By the way I'm not sure redirect_to request.referer is good enough for the security audit.

**Comment by mkasztelnik** [comment]
I agree, maybe `remote: true`, checking if request has xhr, removing json then and adding dedicated javascript would be better?

**Comment by Nuanda** [comment]
Well, I checked my code for a similar thing in PLGData and i think I might be wrong - perhaps this is ok as it is.
